<?php include('../header.php'); ?>
<link rel="stylesheet" href="/css/privacy-policy.min.css">

<!-- Main Content -->
<section id="main-content" class="section-padding">
	<div class="container">
		<h1>WE GOT YOU LLC Terms Of Use</h1>
		<div class="main-txt">
			<p>THE FOLLOWING TERMS AND CONDITIONS (“Terms and Conditions”) govern the use of this website or Services (as defined herein) brought to you (“you”), accessed by you, requested by you or obtained by you and provided by WE GOT YOU LLC, a Florida Limited Liability Company, its parent or one of its subsidiaries, and any content, material, services, features or functionality available by or through this website, including any subdomains thereof Services (“Website”). The Website is made available by WE GOT YOU LLC its parent and/or its subsidiaries, (“we” or “us” or “our”) each having adopted the Terms and Conditions in relation to its Website. We may change the Terms and Conditions from time to time as we may deem fit (in our sole discretion), without notice to you, by posting said changes on the Website. BY USING THE WEBSITE, OTHERWISE ACCESSING THE WEBSITE AND USING THE SERVICES PROVIDED BY WE GOT YOU LLC, OR CLICKING TO ACCEPT OR AGREE TO THESE TERMS AND CONDITIONS WHERE THAT OPTION IS MADE AVAILABLE, YOU HEREBY ACCEPT AND AGREE TO (1) THESE TERMS AND CONDITIONS IN RELATION TO YOUR USE OF THE WEBSITE, (2) WE GOT YOU LLC SERVICES; AND (3) DISCLOSURE AND OTHER HANDLING OF INFORMATION AS DESCRIBED IN OUR PRIVACY POLICY. If you fail to agree to these Terms and Conditions, you will be denied access and any other use of the Website.</p> 

			<h2>Eligibility.</h2>
			<p>You hereby represent and warrant that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties as set forth in these Terms and Conditions and that you are able to and will comply with the terms contained herein. In order to engage WE GOT YOU LLC for any of the Services (as defined below) it offers to potential and current customers, You must be able to represent and warrant that you are of 18 years of age or older, you are not listed on any U.S. Government or foreign government list of prohibited or restricted parties, and you will abide at all times by these Terms and Conditions and any other agreements between you and WE GOT YOU LLC regarding your use of the Services and the Website. If you do not meet the eligibility requirements of this section, then you are not authorized to use the Website or Services.</p>

			<h2>Services.</h2>
			<p>WE GOT YOU LLC is lifestyle management, travel planning and event coordination company. One or more membership program may be offered to individuals at any given time and are subject to change as to types of services offered to such members as well as fees associated with same. When an individual pays a membership fee for a particular type of membership program, that individual will have access to the services provided under that membership program for the duration of the term associated with such plan. Depending on the type of membership plan, “Services” may include preferential rates with airlines and hotels, upgrades when applicable, exclusive access and invitations to member events, and recommendations and bookings to restaurants, bars, sporting events and theaters.  The aforementioned list of Services is non-exclusive in nature, may be modified from time to time at the sole discretion of WE GOT YOU LLC, and varies depending on the type of membership plan held by an individual. The Website contains all information related to the package of Services attached to each type of membership package. You understand and agree that you are not entitled to any Services that are not specifically attached to the membership plan you choose as stated on the Website.</p>

			<h2>Conditions of Participation.</h2>
			<p>In order to participate in one of our membership plans and receive any of the Services attached thereto, you must provide us with your full name, email address, phone number, place of residence and any other required personal information we may ask for from time-to-time. We do not guarantee you the right to participate in all of our membership programs; some programs may be offered to certain individuals by invitation-only. If you provide any information that is inaccurate, not current or incomplete, we may deny you access to Services or terminate your membership plan, at our sole discretion and without any obligation to return any fees paid in relation to your membership plan. As a result of your use of the Website and/or Services, you may receive certain commercial communications from us or third parties. You understand and agree that these communications are part of your willful use of the Website and/or Services, and that, to the extent required by law, you may opt out of receiving these communications (i.e. WE GOT YOU LLC newsletters) at any time by either using the unsubscribe functionality or sending an email to info[at]wgylifestyle[dot]com. Following such an opt-out, we may still communicate with you via email to the extent permitted by applicable law.</p>

			<h2>Membership Policy.</h2>
			<p>WE GOT YOU LLC offers multiple membership plans generally lasting one year in length and requiring an up-front fee in addition to monthly fees. WE GOT YOU LLC reserves the right to offer membership plans for different lengths of time and with various attached fee structures. Membership plan criteria concerning fees and length may be listed on the Website. You agree to make all payments under the applicable membership plan, including all monthly payments contained therein, as a result of opting in to any such membership plan.</p>

			<h2>Proprietary Rights.</h2>
			<p>We own, solely and exclusively, all rights, title and interest in and to the Website, including all material, content (including, without limitation, audio, photographs, illustrations, graphics, video, other visuals, text, software, titles, etc.) code, and data found thereon. Additionally, we own, solely and exclusively, the look, design and organization of the Website, and any compilation of the material, content data on the Website, including, without limitation, any copyrights, trademark rights, patent rights, data base rights, sui generis rights, moral rights and any and all other intellectual property and proprietary rights therein. You hereby acknowledge that your use of the Website does not grant you any ownership to any material, content or data that you may access by or through your use of the Website.</p>

			<h2>Trademarks.</h2>
			<p>The trademarks, logos, service marks and trade names (“Trademarks”) displayed by or through the Website are our registered and unregistered Trademarks and may not be used in connection with products and/or services that are not related to, associated with, or sponsored by their applicable rights holders that are likely to cause customer confusion, or in any manner that discredits, tarnishes or disparages their rights holders. All Trademarks not owned by us that are found on the Website or through the Services are the property of their respective owner. Nothing contained on the Website shall be construed as granting, by implication or otherwise, any license or right to use any Trademark displayed on the Website without our prior written consent or the third party that may own the applicable Trademark. You hereby acknowledge that your misuse of the Trademarks displayed by or through the Website, or any of the Website’s services, is strictly prohibited.</p> 

			<h2>User Information.</h2>
			<p>During the course of your use of the Website and/or the services provided by or through the Website, you may be asked to provide certain personalized information to us (“User Information”). Our information collection and use policies with respect to the privacy of User Information can be found in the Website’s Privacy Policy, which is incorporated herein by reference for all purposes. You hereby acknowledge and agree that you are solely responsible for the accuracy and content of User Information.</p> 

			<h2>Prohibited User Conduct.</h2>
			<p>You hereby agree that during the course of your use of the Website and the Services, features and functionality provided by or through the Website, you shall not: (a) impersonate any person or entity or misrepresent your affiliation with any person or entity; (b) attempt to gain unauthorized access to other computer systems or data through the Website; or (c) use the Website or the Services in violation of any applicable law. You further agree that you shall not attempt, or encourage or support others to attempt, to circumvent, reverse engineer, decrypt, or otherwise modify or interfere with the Website or the Services, or any material or content thereof, or make any unauthorized use thereof. You hereby acknowledge and agree that you shall not use the Website in any manner that could interfere with any other party’s use and enjoyment of the Website or any Services.</p>

			<h2>Indemnification.</h2>
			<p>You hereby agree to defend, indemnify and hold us and our affiliates and our affiliates’ directors, officers, members, employees, lawyers and agents harmless from any and claims, liabilities, costs and expenses, including attorneys’ fees, arising in shape or form from your use of the Website, Services, or your breach or violation of the law or these Terms and Conditions. We reserve the right, at our own defense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with our defense of such claim.</p>

			<h2>Orders for Services.</h2>
			<p>From time to time, we may make certain Services available to visitors and registrants of the Website. If you order any Services, including those affiliated with any membership plans and the membership plans themselves, you hereby represent and warrant that you are eighteen (18) years or older. Furthermore, you agree to pay in full the prices of any such purchases you may make either by credit/debit card concurrent with your online or telephone order or by other payment means made acceptable by us. You agree to pay all applicable taxes. If payment is not received by us from your credit or debit card issuer or its agents, you agree to pay all amounts due upon demand by us.</p>

			<h2>Third Party Websites.</h2>
			<p>The Website may link to third party websites and third party websites may link to the Website (“Linked Sites”). You acknowledge and agree that we have no responsibility for the information, content, products, services, advertising, data or other materials that may or may not be provided by or through Linked Sites, even if the Linked Sites are run or owned by one of our affiliates. Links to Linked Sites do not constitute, or imply, an endorsement or sponsorship by us of such websites, or the information, content, products, services, advertising, data or other materials presented on or through such websites. WE GOT YOU LLC, disclaims any liability for links (a) from another website to this Website; and (b) to another website from this Website. WE GOT YOU LLC, cannot and will not guarantee the standards of any website to which links are provided on this Website nor shall we be held responsible for the materials and content on such websites, or any subsequent links. We do not represent or warrant that the materials and contents of any third party website are accurate, compliant with state or federal law, or compliant with copyright or other intellectual property laws. We are not responsible for any form of transmission received from any linked website. Furthermore, any reliance on the materials and contents of a third party website is done at your own risk, and you assume all responsibilities and consequences resulting from such reliance.</p>

			<h2>Copyright Agent.</h2>
			<p>If you believe that your work has been copied on or through the Website in a way that may constitute copyright infringement, you must forward the following information to our Copyright Agent, designated as such pursuant to the Digital Millennium Copyright Act (DMCA), 17 U.S.C. § 512(c)(2):</p>

			<ul>
				<li>I - Your address, telephone number, and email address;</li>
				<li>II - A description of the copyrighted work claimed to have been infringed;</li>
				<li>III - A description of where the alleged infringing material is located;</li>
				<li>IV - A statement expressing your good faith belief that the alleged use in question is not authorized by the rightful copyright owner, its agent, or the law;</li>
				<li>V - A signature (electronic or physical) of the person authorized to act on behalf of the owner of the copyright interest; and</li> 
				<li>VI - A statement, made under penalty of perjury, that the above information in your notice is truthful and accurate, and that you are the copyright owner or are authorized to act on the copyright owner’s behalf</li>
			</ul>

			<p>FOR DMCA NOTICES ONLY:
			Copyright Agent:<br>
			HEITNER LEGAL, P.L.L.C.<br>
			Phone:	 954-558-6999<br>
			Fax: 	954-927-3333<br>
			Email:	darren@heitnerlegal.com <br>
			Non-copyright inquires will not be addressed by the Copyright Agent</p>

			<p>For Customer Service, please contact<br>
			WE GOT YOU LLC, Customer Service<br>
			1815 PURDY AVENUE<br>
			Miami Beach, FL 33139</p>

			<h2>LIMITATION OF LIABILITY.</h2> 
			<p>IN NO EVENT, INCLUDING, WITHOUT LIMITATION, NEGLIGENCE, SHALL WE, OUR AFFILIATES, OR ANY OF OUR DIRECTORS, OFFICERS, MEMBERS, LAWYERS, EMPLOYEES, AGENTS OR CONTENT OR SERVICE PROVIDERS (“PROTECTED ENTITIES”) BE HELD LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES ARISING FROM, OR DIRECTLY OR INDIRECTLY RELATING TO, THE USE OF, OR THE INABILITY TO USE, THE WEBSITE OR SERVICES OR THE MATERIALS, CONTENT, FEATURES, AND FUNCTIONS RELATED THERETO, OR YOUR SUPPLIANCE OF INFORMATION VIA THE WEBSITE, LOST BUSINESS OR SALES, EVEN IF SUCH PROTECTED ENTITY HAS BEEN ADVISED OF THE POSSIBLITY OF SUCH DAMAGES. IN NO EVENT SHALL THE PROTECTED ENTITIES BE LIABLE FOR OR IN CONNECTION WITH ANY CONTENT POSTED, TRANSMITTED, EXCHANGED OR RECEIVED BY OR ON BEHALF OF ANY USER OR OTHER PERSON ON OR THROUGH THE WEBSITE. IN NO EVENT SHALL THE TOTAL AGGREGATE OF LIABILITY OF THE PROTECTED ENTITIES FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING FROM THESE TERMS AND CONDITIONS OR YOUR USE OF THE WEBSITE EXCEED, IN THE AGGREGATE, THE AMOUNT, IF ANY, PAID BY YOU TO US FOR YOUR USE OF THE WEBSITE, SERVICES, OR ANY PRODUCTS PURCHASED VIA THE WEBSITE.</p>

			<h2>DISCLAIMER OF WARRANTIES.</h2>
			<p>THE WEBSITE, INCLUDING, WITHOUT LIMITATION, ALL SERVICES, CONTENT, FEATURES, MATERIALS AND FUNCTIONS PROVIDED BY OR THROUGH THE WEBSITE, IS PROVIDED “AS IS,” WITHOUT WARRANT OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY FOR INFORMATION, DATA, UPTIME OR UNINTERRUPTED ACCESS, ANY WARRANTIES CONCERNING THE AVAILABILITY, PLAYABILITY, ACCURACY, DISPLAYABILITY, COMPLETENESS, USEFULNESS, OR CONTENT OF INFORMATION, AND ANY WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTCULAR PURPOSE. WE HEREBY DISCLAIM ANY AND ALL SUCH WARRANTIES, EXPRESS AND IMPLIED. WE DO NOT WARRANT THAT THE WEBSITE OR THE SERVICES, CONTENT, FUNCTIONS OR MATERIALS PROVIDED BY OR THROUGH THE WEBSITE WILL BE TIMELY, SECURE, UNINTERRUPTED OR ERROR FREE, OT THAT DEFECT WILL BE CORRECTED. WE MAKE NO WARRANTY THAT THE WEBSITE OR THE PROVIDED SERVICES WILL MEET USER’S EXPRESS OR IMPLIED REQUIREMENTS. NO INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR THROUGH THE WEBSITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. WE AND OUR AFFILIATES ASSUME NO RESPONSIBILITY, AND SHALL NOT BE HELD LIABLE FOR, ANY DAMAGES TO, OR VIRUSES THAT MAY INFECT, YOUR EQUIPMENT ON ACCOUNT OF YOUR ACCESS, USE, OR BROWSING OF THE WEBSITE OR ANY DOWNLOADING OF MATERIALS, CONTENT, TEXT, IMAGES, VIDEO OR AUDIO CONTENT FROM THE WEBSITE. IF YOUR ARE DISSATISFIED WITH THE WEBSITE AND/OR ITS SERVICES, YOUR SOLE REMEDY IS TO DISCONTINUE USING THE WEBSITE AND/OR ITS SERVICES.</p>

			<p>WE ATTEMPT TO ENSURE THAT THE INFORMATION POSTED ON THE WEBSITE IS CORRECT AND CURRENT. WE RESERVE ALL RIGHT TO CHANGE OR EDIT ANY OF THE INFORMATION PROVIDED ON THE WEBSITE AT ANY TIME AND WITHOUT PRIOR NOTICE TO YOU. WE NEITHER ENDORSE NOR ARE RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE OR STATEMENT ON THE WEBSITE, NOR FOR ANY OFFENSIVE, DEFAMATORY, VULGAR, UNLAWFUL OR INFRINGING POSTING MADE THEREON BY ANY PERSON OTHER THAN OUT AUTHORIZED EMPLOYEE SPOKESPERSONS WHILE ACTING IN THEIR OFFCIAL CAPACITIES. IT IS YOUR SOLE RESPONSIBILITY TO EVALUATE THE TRUTHFULNESS, COMPLETENESS OR USEFULNESS OF ANY MATERIAL, OPINION, ADVICE OR OTHER INFORMATION MADE AVAILABLE BY OR THROUGH THE WEBSITE.</p> 

			<p>WE SHALL HAVE NO LIABILITY FOR INVESTMENT DECISIONS BASED UPON, OR THE RESULTS OBTAINED FROM, THE CONTENT PROVIDED BY OR THROUGH THE WEBSITE. NOTHING CONTAINED IN THE WEBSITE SHALL BE CONSTRUED AS INVESTMENT ADVICE.</p>

			<p>WITHOUT LIMITING THE ABOVE, WE AND OUR AFFILIATES, SUPPLIERS AND LICENSORS MAKE NO WARRANTIES OR REPRESENTATIONS RELATING TO ANY PRODUCTS OR SERVICES ORDERED OR PROVIDED VIA THE WEBSITE. WE HEREBY DISCLAIM, AND YOU HEREBY WAIVE, ANY AND ALL WARANTIES AND REPRESENTATIONS MADE IN PRODUCT OR SERVICES LITERATURE, FREQUENTLY ASKED QUESTIONS (FAQs), DOCUMENTS AND OTHERWISE ON THE WEBSITE OR IN CORRESPONDENCE WITH US OR OUR AGENTS. ANY PRODUCTS OR SERVICES ORDERED OR PROVIDED VIA THE WEBSITE ARE PROVIDED “AS IS,” EXCEPT TO THE EXTENT, IF AT ALL, OTHERWISE SET FORTH IN A LICENSE OR SALE AGREEMENT SEPEARATELY ENTERED INTO BY WRITING BETWEEN YOU AND US OR OUR LICENSOR AND SUPPLIER.</p>

			<h2>Applicable Laws.</h2>
			<p>The Website is controlled and operated from our offices in the United States of America, and we do not represent that materials provided by or through the Website are appropriate or available for use in other countries and/or territories. Users who choose to access or otherwise the Website and its services from other locations do so on their own accord, and are solely responsible for compliance with local laws, to the extent applicable. All parties to these Terms and Conditions hereby waive their right to a trial by jury.</p> 

			<h2>Termination.</h2>
			<p>We may terminate, modify, suspend or discontinue any aspect of the Website or Services at any time without prior notice. We may restrict, suspend or terminate your access to the Website and/or Services if we believe, in our sole discretion, that you are in breach of these Terms and Conditions, applicable law or for any other reason without notice or liability.</p>

			<h2>Changes to Terms of Use.</h2>
			<p>We reserve the right to change, modify, add or remove any part of these Terms and Conditions, in whole or in part, at any time, in our sole discretion, without prior notice. Changes in these Terms and Conditions will become immediately effective upon posting. You hereby acknowledge and agree that your continued use of the Website and/or Services made available by or through the Website after any changes to the Terms and Conditions are posted will be considered acceptance of such changes.</p>

			<h2>Miscellaneous.</h2>
			<p>The Terms and Conditions, and the relationship between you and us, shall be governed by the laws of the State of Florida, United States of America. You hereby agree that any cause of action that may arise under these Terms and Conditions shall take place and be heard in the appropriate court in the State of Florida, Miami-Dade County. You hereby agree to be subject to the personal and exclusive jurisdiction of the courts located within Miami-Dade County in the State of Florida. Failure to exercise or enforce any right or provision contained herein these Terms and Conditions shall not constitute a waiver of such right or provision. If any provision of these Terms and Conditions is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should give maximum effect to the parties’ intentions as reflected in such provision, and that the other provisions of these Terms and Conditions shall remain in full force and effect.</p>
		</div>
	</div>
</section>
<!-- End Main Content -->

<?php include('../footer.php'); ?>